# Generated by Django 2.2.1 on 2019-05-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190526_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
