# Generated by Django 2.0.2 on 2019-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Document',
        ),
    ]
